# Generated by Django 2.0.2 on 2018-12-14 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shujuku',
            fields=[
                ('zhbh', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stsl', models.CharField(blank=True, max_length=100)),
                ('cwbh', models.TextField()),
                ('gxsj', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
