# Generated by Django 2.0.2 on 2018-12-14 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuming', models.CharField(max_length=100)),
                ('zuozhe', models.CharField(max_length=100)),
                ('shijian', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
