# Generated by Django 2.0.2 on 2018-12-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('shuming', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('zuozhe', models.CharField(max_length=100)),
                ('shijian', models.CharField(max_length=100)),
            ],
        ),
    ]
